### ISSUE TITLE
Libsmbclient does not support anonymous links

### ISSUE THREAD

**Issue by huaibaobao2017** [mpvkit/MPVKit#21]
Libsmbclient seems to not support guest anonymous playback links,
such as: smb://guest@server/share/filename. mp4 
smb://guest:@server/share/filename. mp4 
smb://server/share/filename.mp4 . 
If possible, what should the complete link be? Can it be replaced with libdsm?

work find with follow:
smb://username:password@server/share/filename. mp4

**Comment by huaibaobao2017** [comment]
[stream_callback] v: Opening smb://192.168.1.105/Users/2.mp4
[ffmpeg] v: Opening smb://192.168.1.105/Users/2.mp4
[ffmpeg] error: smb: File open failed: Invalid argument
[stream] error: Failed to open smb://192.168.1.105/Users/2.mp4.
[cplayer] v: Opening failed or was aborted: smb://192.168.1.105/Users/2.mp4
event: end-file
event: idle

**Comment by cxfksword** [comment]
I tested it's OK, Perhaps the anonymous access for your SMB server is not configured correctly.

**Comment by huaibaobao2017** [comment]
> I tested it's OK, Perhaps the anonymous access for your SMB server is not configured correctly.

No, I have tried other apps and they all play normally. Simulators and real machines both have the same error.

**Comment by cxfksword** [comment]
What's the type and samba protocol version of your samba server? Maybe libsambaclient isn't compatible with it.

**Comment by huaibaobao2017** [comment]
Neither SMB1.0 nor SMB3.0 works

<img width="413" alt="截屏2024-10-16 15 10 48" src="https://github.com/user-attachments/assets/1741e242-8232-4994-ba23-35f39317c9b7">

**Comment by cxfksword** [comment]
Libsmbclient is incompatible with anonymous access to Windows share. You can attach a default guest account when connecting to it.
