### ISSUE TITLE
Under macOS, Libbluray does not seem to be effective. 

### ISSUE THREAD

**Issue by huaibaobao2017** [mpvkit/MPVKit#25]
version 0.39

[bd] v: Opening bd://
disc.c:333: failed opening UDF image file:///Users/bb/Downloads/videos/bd/APOLLO_11
disc.c:437: error opening file BDMV/index.bdmv
disc.c:437: error opening file BDMV/BACKUP/index.bdmv
[bd] error: Couldn't open Blu-ray device: file:///Users/bb/Downloads/videos/bd/APOLLO_11
[stream_callback] v: Opening bd://
[stream] error: No protocol handler found to open URL bd://
[stream] error: The protocol is either unsupported, or was disabled at compile-time.
[cplayer] v: Opening failed or was aborted: bd://
event: end-file
event: idle
[cplayer] v: finished playback, loading failed (reason 4)

<img width="730" alt="截屏2024-10-28 16 32 34" src="https://github.com/user-attachments/assets/37ec25df-3971-4664-8122-c92adfbc68cd">

**Comment by cxfksword** [comment]
Ensure app has authorized file access to the `Downloads` directory and remove `file://` prefix
