### ISSUE TITLE
Custom FFmpeg

### ISSUE THREAD

**Issue by adrianguanipa** [mpvkit/MPVKit#28]
Hi there,

How can I build this while using a custom FFmpeg version? Under the /dist folder I see FFmpeg-n7.1 is getting downloaded for the project, but replacing that before running make build doesn't seem to be doing the trick.

Thanks

**Comment by cxfksword** [comment]
The version needs to be changed in file:
https://github.com/mpvkit/MPVKit/blob/919207967244c1784c08c1c0fb2b6a3a2ec8a62d/Sources/BuildScripts/XCFrameworkBuild/main.swift#L53

**Comment by adrianguanipa** [comment]
> The version needs to be changed in file:
> 
> https://github.com/mpvkit/MPVKit/blob/919207967244c1784c08c1c0fb2b6a3a2ec8a62d/Sources/BuildScripts/XCFrameworkBuild/main.swift#L53

Thanks
