### ISSUE TITLE
Libshaderc has an invalid CFBundleIdentifier

### ISSUE THREAD

**Issue by bryandunbar** [mpvkit/MPVKit#7]
I'm trying to use the LGPL version but am getting `This bundle is invalid. The bundle at path Payload/Tablo-tvOS.app/Frameworks/Libshaderc_combined.framework has an invalid CFBundleIdentifier 'com.kintan.ksplayer.Libshaderc_combined'` when pushing to TF. Is there a specific branch that fixes this?

**Comment by cxfksword** [comment]
`main` branch has updated libshaderc CFBundleIdentifier, You can try to see if it solves the issue.

**Comment by bryandunbar** [comment]
Thx @cxfksword. We are able to process for TF now!

**Comment by stonerl** [comment]
> `main` branch has updated libshaderc CFBundleIdentifier, You can try to see if it solves the issue.

Could you push a new release? Like 0.38.0_1 or so? We switched to the new repo and can't pull in MPVKit as a dependency becasue the mismatching libshaderc CFBundleIdentifier.

**Comment by stonerl** [comment]
Checking out the main branch now gives me this error:

```
checksum of downloaded artifact of binary target 'Libshaderc_combined'

(2a9d485336d64ac36d148c3ebc1194e980b36e6e8a419f03ed4e4b5bca7e2a9c)

does not match checksum specified by the manifest 

(f6267f62881e9496608069266ba52b025bcfcd6ec5859d02d780feeabfacc947)
```

**Comment by cxfksword** [comment]
> Checking out the main branch now gives me this error:
> 
> ```
> checksum of downloaded artifact of binary target 'Libshaderc_combined'
> 
> (2a9d485336d64ac36d148c3ebc1194e980b36e6e8a419f03ed4e4b5bca7e2a9c)
> 
> does not match checksum specified by the manifest 
> 
> (f6267f62881e9496608069266ba52b025bcfcd6ec5859d02d780feeabfacc947)
> ```

It seems that  SPM meet cache problem, you need to delete all old package cache.

**Comment by stonerl** [comment]
I already did this. Deletes the Build Folder and also `Reset the Package Caches`

**Comment by cxfksword** [comment]
> I already did this. Deleted the Build Folder and also `Reset the Package Caches`

You can try delete all SPM cache:
```
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/org.swift.swiftpm
```

**Comment by arekf** [comment]
> > I already did this. Deleted the Build Folder and also `Reset the Package Caches`
> 
> You can try delete all SPM cache:
> 
> ```
> rm -rf ~/Library/Caches/org.swift.swiftpm
> rm -rf ~/Library/org.swift.swiftpm
> ```

It does not solve the issue, tested on a clean macOS installation

**Comment by cxfksword** [comment]
I publish new version `0.38.0-fix`, need to specify using this version to fix this.

**Comment by stonerl** [comment]
@cxfksword thanks that one works
